use_frameworks!

platform :ios, '10.0'

target 'CNjacob_CoreBluetooth_Example' do
  pod 'CNjacob_CoreBluetooth', :path => '../'

  target 'CNjacob_CoreBluetooth_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
